### ISSUE TITLE
Correction to bhy procedure

### ISSUE THREAD

**Issue by miheerdew** [jpalowitch/bmd#19]
The same bug also seems to be there in this function. Should I replace this cumsum with sum too?
https://github.com/jpalowitch/bmd/blob/master/bmd.R#L96

**Comment by jpalowitch** [comment]
No, I left that one as-is to compare the wrong version. So, update 6 runs both the kbodwin/DCM variance calculation, and the wrong bhy procedure. Update 5 runs our variance calculation, and the correct bhy procedure (as implemented in bh_reject). You no longer should be doing any sims with update6. Andrew has confirmed with me that approach is not right.

**Comment by miheerdew** [comment]
initialize3 was using bhy. I'll change that. Should I just remove bhy?

**Comment by miheerdew** [comment]
Okay. I think I'll keep it for now. It seems to be used at many places.

**Comment by jpalowitch** [comment]
Just keep the function in for now. Change the initialize3 method to bh_reject. bhy should only be being used in update6 at this point...anywhere else, change to bh_reject.
